name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Cho phép bấm nút chạy thủ công để test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Lấy source code về
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Go để chạy test (Optional - nhưng nên có để đảm bảo code sạch)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      
      - name: Run Unit Tests
        run: go test ./...

      # 3. Setup Docker Buildx (Công cụ build đa nền tảng)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Đăng nhập Docker Hub bằng Secret có sẵn
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build và đẩy lên Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Tự động gắn tag: latest và hash của commit
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pomai_server:pomai-cache
            ${{ secrets.DOCKERHUB_USERNAME }}/pomai_server:pomai-cache-${{ github.sha }}